version: "3"

tasks:
  build:
    desc: Build the application
    cmds:
      - go build -o bin/banner ./cmd/banner
    sources:
      - ./cmd/banner/**/*.go
      - ./internal/**/*.go
    generates:
      - bin/banner

  run:
    desc: Run the application
    cmds:
      - go run ./cmd/banner
    deps: [build]

  test:
    desc: Run tests
    cmds:
      - go test ./tests/...
    env:
      ENVIRONMENT: test

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test -coverpkg=./internal/... -cover ./tests/...
    env:
      ENVIRONMENT: test

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - go clean -cache
      - go clean -modcache

  dev:
    desc: Run in development mode
    cmds:
      - go run ./cmd/banner
    env:
      ENVIRONMENT: development
