// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAction } from "./AdminAction";
import type { AdminEntity } from "./AdminEntity";

/**
 * Query params for `GET /api/admin/action-log`.
 */
export type ActionLogParams = { 
/**
 * Discord ID of the acting admin, as a string to survive JSON precision.
 */
actor?: string | null, action?: AdminAction | null, entityType?: AdminEntity | null, entityId?: string | null, since?: string | null, until?: string | null, page?: number | null, perPage?: number | null, };
