// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of record an action targeted.
 */
export type AdminEntity = "instructor" | "user" | "term" | "bluebook_link";
