// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAction } from "./AdminAction";
import type { AdminEntity } from "./AdminEntity";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One recorded action, as stored and as served.
 */
export type AdminAuditEntry = { id: number, createdAt: string, actorDiscordId: string, actorUsername: string, action: AdminAction, entityType: AdminEntity, entityId: string | null, relatedIds: Array<string>, detail: JsonValue, };
