// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an admin did. Stored as text, so adding a variant needs no migration.
 */
export type AdminAction = "instructor_merge" | "instructor_merge_claimant" | "instructor_merge_all" | "instructor_dismiss" | "instructor_undismiss" | "rmp_accept_candidate" | "rmp_reject_candidate" | "rmp_reject_all" | "rmp_unmatch" | "bluebook_approve_link" | "bluebook_reject_link" | "bluebook_assign_link" | "user_set_admin" | "term_enable" | "term_disable";
