// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAuditEntry } from "./AdminAuditEntry";

/**
 * A page of entries, with the unpaginated total behind it.
 */
export type AdminAuditPage = { entries: Array<AdminAuditEntry>, total: number, page: number, perPage: number, };
