// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceStatus } from "./ServiceStatus";

export type AdminServiceInfo = { name: string, status: ServiceStatus, };
