// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiErrorCode } from "./ApiErrorCode";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Standardized error response for all API endpoints.
 */
export type ApiError = { 
/**
 * Machine-readable error code
 */
code: ApiErrorCode, 
/**
 * Human-readable error message
 */
message: string, 
/**
 * Optional additional details (validation errors, field info, etc.)
 */
details: JsonValue | null, };
