// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Standardized error response for all API endpoints.
 */
export type ApiError = { 
/**
 * Machine-readable error code (e.g., "NOT_FOUND", "INVALID_TERM")
 */
code: string, 
/**
 * Human-readable error message
 */
message: string, 
/**
 * Optional additional details (validation errors, field info, etc.)
 */
details: JsonValue | null, };
