// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /api/admin/bluebook/links/{id}/assign`.
 */
export type AssignBody = { instructorId: number, };
