// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Course attribute codes from Banner.
 */
export type Attribute = { "type": "CoreCommunication" } | { "type": "CoreMathematics" } | { "type": "CoreLifePhysicalSciences" } | { "type": "CoreLanguagePhilosophy" } | { "type": "CoreCreativeArts" } | { "type": "CoreAmericanHistory" } | { "type": "CoreGovernment" } | { "type": "CoreSocialBehavioral" } | { "type": "CoreComponentArea" } | { "type": "Developmental" } | { "type": "LowerDivision" } | { "type": "UpperDivision" } | { "type": "Graduate" } | { "type": "Honors" } | { "type": "LowCostTextbooks" } | { "type": "FreeTextbooks" } | { "type": "Leadership" } | { "type": "ServiceLearning" } | { "type": "FinishAtUT" } | { "type": "UndergraduateResearch" } | { "type": "Unknown", code: string, description: string, };
