// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditLogEntry } from "./AuditLogEntry";

export type AuditLogResponse = { entries: Array<AuditLogEntry>, };
