// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type AuditLogEntry = { id: number, courseId: number, timestamp: string, fieldChanged: string, oldValue: JsonValue | null, newValue: JsonValue, subject: string | null, courseNumber: string | null, crn: string | null, courseTitle: string | null, termCode: string | null, };
