// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BluebookLinkCourse } from "./BluebookLinkCourse";

/**
 * Detail view for a single BlueBook link.
 */
export type BluebookLinkDetail = { id: number, instructorName: string, subject: string | null, status: string, confidence: number | null, instructorId: number | null, instructorDisplayName: string | null, evalCount: number, courses: Array<BluebookLinkCourse>, };
