// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * BlueBook summary for instructor list cards.
 */
export type BlueBookListSummary = { avgInstructorRating: number, totalResponses: number, };
