// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Brief BlueBook evaluation data for an instructor.
 */
export type BlueBookBrief = { avgInstructorRating: number, totalResponses: number, };
