// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A BlueBook link row in the paginated list view.
 */
export type BluebookLinkListItem = { id: number, instructorName: string, subject: string | null, status: string, confidence: number | null, instructorId: number | null, instructorDisplayName: string | null, evalCount: number, };
