// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A course associated with a BlueBook link (via evaluations).
 */
export type BluebookLinkCourse = { subject: string, courseNumber: string, term: string, instructorRating: number | null, courseRating: number | null, };
