// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for the auto-matching pipeline.
 */
export type BluebookMatchResponse = { 
/**
 * Names processed in this run.
 */
totalNames: number, 
/**
 * High-confidence matches (status = 'auto').
 */
autoMatched: number, 
/**
 * Lower-confidence matches needing review (status = 'pending').
 */
pendingReview: number, 
/**
 * No match found at all (status = 'pending', no instructor_id).
 */
noMatch: number, 
/**
 * Names with approved/rejected links that were left untouched.
 */
skippedManual: number, 
/**
 * Stale auto/pending links deleted before re-matching.
 */
deletedStale: number, };
