// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate status counts for the link list.
 */
export type BluebookLinkStats = { total: number, auto: number, pending: number, approved: number, rejected: number, };
