// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full BlueBook summary for instructor detail pages.
 */
export type BlueBookFull = { calibratedRating: number, avgInstructorRating: number, avgCourseRating: number | null, totalResponses: number, evalCount: number, };
