// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * BlueBook evaluation summary for course search results.
 */
export type BlueBookRating = { avgInstructorRating: number, totalResponses: number, isConfident: boolean, };
