// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Review state of an `instructor_bluebook_links` row.
 *
 * `Auto` and `Pending` are algorithm-generated; the other two are human decisions.
 */
export type BluebookLinkStatus = "auto" | "pending" | "approved" | "rejected";
