// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Physical or virtual campus where a course is offered.
 */
export type Campus = { "type": "Main" } | { "type": "Downtown" } | { "type": "Southwest" } | { "type": "Laredo" } | { "type": "Internet" } | { "type": "OnlinePrograms" } | { "type": "Unknown", code: string, description: string, };
