// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoreBreakdown } from "./ScoreBreakdown";

/**
 * A match candidate in the detail view.
 */
export type CandidateResponse = { id: number, rmpLegacyId: number, firstName: string, lastName: string, department: string | null, avgRating: number | null, avgDifficulty: number | null, numRatings: number, wouldTakeAgainPct: number | null, score: number, scoreBreakdown: ScoreBreakdown, status: string, 
/**
 * Subject prefixes extracted from RMP reviews (e.g. ["CS", "WRC"]).
 */
reviewSubjects: Array<string>, 
/**
 * Distinct years in which this professor received reviews.
 */
reviewYears: Array<number>, 
/**
 * Instructor already holding this RMP profile, if any.
 */
claimedBy: string | null, 
/**
 * Why this candidate was not linked automatically.
 */
blockedReason: string | null, };
