// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoreBreakdown } from "./ScoreBreakdown";

/**
 * A match candidate in the detail view.
 */
export type CandidateResponse = { id: number, rmpLegacyId: number, firstName: string | null, lastName: string | null, department: string | null, avgRating: number | null, avgDifficulty: number | null, numRatings: number | null, wouldTakeAgainPct: number | null, score: number | null, scoreBreakdown: ScoreBreakdown | null, status: string, 
/**
 * Subject prefixes extracted from RMP reviews (e.g. ["CS", "WRC"]).
 */
reviewSubjects: Array<string>, 
/**
 * Distinct years in which this professor received reviews.
 */
reviewYears: Array<number>, };
