// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodeDescription = { code: string, description: string, 
/**
 * Typed filter string for query params (e.g. "Online.Async", "Main", "raw:XYZ").
 */
filterValue: string, };
