// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CohortPeer } from "./CohortPeer";
import type { Evidence } from "./Evidence";

/**
 * An instructor's rating on one course, set against everyone else who teaches it.
 */
export type CohortCourse = { subject: string, courseNumber: string, 
/**
 * Response-weighted mean `BlueBook` instructor rating across this course's sections.
 */
rating: number, responses: number, sections: number, cohortMean: number, 
/**
 * Absent for a cohort of one.
 */
cohortSd: number | null, cohortSize: number, 
/**
 * 1 is the highest-rated; absent when nobody else teaches the course.
 */
rank: number | null, 
/**
 * `rating - cohort_mean`; absent when nobody else teaches the course.
 */
delta: number | null, 
/**
 * Half-width of the 95% interval on `rating`.
 */
halfWidth: number, evidence: Evidence, 
/**
 * The rest of the cohort, highest-rated first.
 */
peers: Array<CohortPeer>, };
