// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Evidence } from "./Evidence";

/**
 * Where an instructor sits among all instructors, by mean distance from their cohorts.
 */
export type CohortStanding = { 
/**
 * Response-weighted mean of the per-course deltas.
 */
delta: number, 
/**
 * Share of instructors with a lower delta, 0 to 100.
 */
percentile: number, 
/**
 * Courses with a cohort to compare against.
 */
comparedCourses: number, 
/**
 * Half-width of the 95% interval on `delta`.
 */
halfWidth: number, evidence: Evidence, };
