// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Another instructor who teaches the same course.
 */
export type CohortPeer = { slug: string | null, displayName: string, rating: number, responses: number, };
