// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Composite rating combining BlueBook and RMP via response-count-weighted average.
 */
export type CompositeRating = { score: number, totalResponses: number, };
