// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoreSource } from "./ScoreSource";

/**
 * Bayesian composite rating combining RMP and BlueBook via regression calibration.
 */
export type CompositeRating = { 
/**
 * Posterior mean -- the headline number displayed to users.
 */
displayScore: number, 
/**
 * CI lower bound -- used for ranking (penalizes low confidence).
 */
sortScore: number, ciLower: number, ciUpper: number, 
/**
 * 0.0-1.0 scalar indicating how much data narrowed the posterior.
 */
confidence: number, source: ScoreSource, totalResponses: number, };
