// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scrape target for [`TargetType::CourseRange`]: a numeric course-number span within a subject.
 */
export type CourseRangeTarget = { subject: string, low: number, high: number, term: string | null, };
