// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A suggested course result for autocomplete.
 */
export type CourseSuggestion = { subject: string, courseNumber: string, title: string, sectionCount: number, score: number, };
