// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attribute } from "./Attribute";
import type { Campus } from "./Campus";
import type { CreditHours } from "./CreditHours";
import type { CrossList } from "./CrossList";
import type { DbMeetingTime } from "./DbMeetingTime";
import type { Enrollment } from "./Enrollment";
import type { InstructionalMethod } from "./InstructionalMethod";
import type { InstructorResponse } from "./InstructorResponse";
import type { PartOfTerm } from "./PartOfTerm";
import type { SectionLink } from "./SectionLink";

export type CourseResponse = { crn: string, subject: string, courseNumber: string, title: string, termCode: string, sequenceNumber: string | null, instructionalMethod: InstructionalMethod | null, 
/**
 * Raw instructional method code, included when parsing fails (Tier 1 fallback).
 */
instructionalMethodCode: string | null, campus: Campus | null, enrollment: Enrollment, creditHours: CreditHours | null, crossList: CrossList | null, sectionLink: SectionLink | null, partOfTerm: PartOfTerm | null, meetingTimes: Array<DbMeetingTime>, attributes: Array<Attribute>, isAsyncOnline: boolean, 
/**
 * Best display-ready location: physical room ("MH 2.206"), "Online", or campus fallback.
 */
primaryLocation: string | null, 
/**
 * Whether a physical (non-INT) building was found in meeting times.
 */
hasPhysicalLocation: boolean, primaryInstructorId: number | null, instructors: Array<InstructorResponse>, };
