// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreditHours } from "./CreditHours";
import type { CrossList } from "./CrossList";
import type { DbMeetingTime } from "./DbMeetingTime";
import type { DeliveryMode } from "./DeliveryMode";
import type { Enrollment } from "./Enrollment";
import type { InstructorResponse } from "./InstructorResponse";
import type { SectionLink } from "./SectionLink";

export type CourseResponse = { crn: string, subject: string, courseNumber: string, title: string, termCode: string, sequenceNumber: string | null, instructionalMethod: string | null, campus: string | null, enrollment: Enrollment, creditHours: CreditHours | null, crossList: CrossList | null, sectionLink: SectionLink | null, partOfTerm: string | null, meetingTimes: Array<DbMeetingTime>, attributes: Array<string>, isAsyncOnline: boolean, deliveryMode: DeliveryMode | null, 
/**
 * Best display-ready location: physical room ("MH 2.206"), "Online", or campus fallback.
 */
primaryLocation: string | null, 
/**
 * Whether a physical (non-INT) building was found in meeting times.
 */
hasPhysicalLocation: boolean, primaryInstructorId: number | null, instructors: Array<InstructorResponse>, };
