// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Credit hours for a course section — either a fixed value or a range.
 */
export type CreditHours = { "type": "fixed", hours: number, } | { "type": "range", low: number, high: number, };
