// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scrape target for [`TargetType::CrnList`]: an explicit set of CRNs.
 */
export type CrnListTarget = { crns: Array<string>, term: string | null, };
