// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cross-listed section information.
 */
export type CrossList = { identifier: string, capacity: number, count: number, };
