// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An inclusive date range with the invariant that `start <= end`.
 */
export type DateRange = { start: string, end: string, };
