// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateRange } from "./DateRange";
import type { DayOfWeek } from "./DayOfWeek";
import type { MeetingLocation } from "./MeetingLocation";
import type { TimeRange } from "./TimeRange";

/**
 * Represents a meeting time stored as JSONB in the courses table.
 */
export type DbMeetingTime = { 
/**
 * Time range for the meeting; `None` means TBA.
 */
timeRange: TimeRange | null, 
/**
 * Date range over which the meeting recurs.
 */
dateRange: DateRange, 
/**
 * Active days of the week. Empty means days are TBA.
 */
days: Array<DayOfWeek>, 
/**
 * Physical location; `None` when all location fields are absent.
 */
location: MeetingLocation | null, meetingType: string, meetingScheduleType: string, };
