// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A term record from the database, synced from Banner.
 *
 * Named `DbTerm` to avoid collision with `crate::banner::models::terms::Term`
 * which represents a parsed term code (year + season).
 */
export type DbTerm = { 
/**
 * Term code, e.g., "202510"
 */
code: string, 
/**
 * Description from Banner, e.g., "Fall 2024"
 */
description: string, 
/**
 * Year extracted from code, e.g., 2024
 */
year: number, 
/**
 * Season name: "Fall", "Spring", or "Summer"
 */
season: string, 
/**
 * Whether the scraper should process this term
 */
scrapeEnabled: boolean, 
/**
 * Whether Banner marks this as "View Only"
 */
isArchived: boolean, 
/**
 * When we first discovered this term
 */
discoveredAt: string, 
/**
 * When we last completed a full scrape of this term
 */
lastScrapedAt: string | null, 
/**
 * Record creation timestamp
 */
createdAt: string, 
/**
 * Record update timestamp
 */
updatedAt: string, };
