// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Delivery mode classification for visual accents on location cells.
 *
 * `None` means normal in-person on the main campus (no accent needed).
 */
export type DeliveryMode = "online" | "internet" | "hybrid" | "off-campus";
