// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much evidence there is that two records are the same person.
 */
export type DuplicateTier = "sameAccount" | "missingEmail" | "differentAccount";
