// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much evidence there is that two records are the same person.
 *
 * The two casings differ on purpose: `instructor_merges.tier` stores `snake_case`,
 * while the API and TypeScript union use `camelCase`.
 */
export type DuplicateTier = "sameAccount" | "missingEmail" | "differentAccount";
