// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DuplicatePair } from "./DuplicatePair";

export type DuplicatesResponse = { pairs: Array<DuplicatePair>, 
/**
 * Pairs already judged to be different people, kept so review can undo one.
 */
dismissed: Array<DuplicatePair>, };
