// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DuplicateSide } from "./DuplicateSide";
import type { DuplicateTier } from "./DuplicateTier";

/**
 * Two instructor records that appear to describe the same person.
 */
export type DuplicatePair = { tier: DuplicateTier, survivor: DuplicateSide, loser: DuplicateSide, 
/**
 * Both records teach at least one subject in common.
 */
subjectsOverlap: boolean, };
