// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RmpMatchStatus } from "./RmpMatchStatus";

/**
 * One side of a duplicate pair.
 */
export type DuplicateSide = { id: number, displayName: string, email: string | null, courseCount: bigint, subjects: Array<string>, rmpLegacyIds: Array<number>, matchStatus: RmpMatchStatus, };
