// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enrollment counts for a course section.
 */
export type Enrollment = { current: number, max: number, waitCount: number, waitCapacity: number, };
