// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far the 95% interval on a course rating leaves it from meaning anything.
 */
export type Evidence = "insufficient" | "limited" | "solid";
