// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hybrid delivery sub-variants indicating in-person meeting frequency.
 */
export type HybridVariant = "Half" | "OneThird" | "TwoThirds";
