// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CohortCourse } from "./CohortCourse";
import type { CohortStanding } from "./CohortStanding";

export type InstructorCohort = { 
/**
 * Absent when no course has anyone to compare against.
 */
standing: CohortStanding | null, courses: Array<CohortCourse>, };
