// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlueBookBrief } from "./BlueBookBrief";
import type { InstructorRating } from "./InstructorRating";
import type { RmpBrief } from "./RmpBrief";

/**
 * Nested score bundle returned by API endpoints for instructor contexts.
 * Contains the rating plus raw source data for tooltip display.
 */
export type InstructorScoreBundle = { rating: InstructorRating, rmp: RmpBrief | null, bluebook: BlueBookBrief | null, };
