// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A suggested instructor result for autocomplete.
 */
export type InstructorSuggestion = { id: number, displayName: string, score: number, };
