// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HybridVariant } from "./HybridVariant";
import type { OnlineVariant } from "./OnlineVariant";

/**
 * How a course section is delivered.
 */
export type InstructionalMethod = { "type": "InPerson" } | { "type": "Online", "variant": OnlineVariant } | { "type": "Hybrid", "variant": HybridVariant } | { "type": "Independent" };
