// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RatingSource } from "./RatingSource";

/**
 * Bayesian composite rating combining RMP and BlueBook via regression calibration.
 */
export type InstructorRating = { 
/**
 * Posterior mean -- the headline number displayed to users.
 */
score: number, 
/**
 * CI lower bound -- used for ranking (penalizes low confidence).
 */
rankScore: number, ciLower: number, ciUpper: number, 
/**
 * 0.0-1.0 scalar indicating how much data narrowed the posterior.
 */
confidence: number, source: RatingSource, totalResponses: number, };
