// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RmpMatchStatus } from "./RmpMatchStatus";
import type { TopCandidateResponse } from "./TopCandidateResponse";

/**
 * An instructor row in the paginated list.
 */
export type InstructorListItem = { id: number, displayName: string, email: string | null, rmpMatchStatus: RmpMatchStatus, rmpLinkCount: number, candidateCount: number, courseSubjectCount: number, topCandidate: TopCandidateResponse | null, 
/**
 * Sorted distinct academic years in which this instructor taught courses.
 */
teachingYears: Array<number>, 
/**
 * Sorted distinct subject codes this instructor has taught.
 */
subjectsTaught: Array<string>, };
