// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlueBookBrief } from "./BlueBookBrief";
import type { InstructorRating } from "./InstructorRating";
import type { RmpBrief } from "./RmpBrief";

export type InstructorResponse = { instructorId: number, bannerId: string, displayName: string, firstName: string | null, lastName: string | null, email: string | null, slug: string | null, isPrimary: boolean, rmp: RmpBrief | null, bluebook: BlueBookBrief | null, rating: InstructorRating | null, };
