// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RmpMatchStatus } from "./RmpMatchStatus";

/**
 * Instructor summary in the detail view.
 */
export type InstructorDetail = { id: number, displayName: string, email: string | null, rmpMatchStatus: RmpMatchStatus, subjectsTaught: Array<string>, courseCount: number, 
/**
 * Sorted distinct academic years in which this instructor taught courses.
 */
teachingYears: Array<number>, };
