// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlueBookRating } from "./BlueBookRating";
import type { CompositeRating } from "./CompositeRating";
import type { RmpRating } from "./RmpRating";

/**
 * Nested score object returned by API endpoints for instructor contexts.
 * Contains the composite score plus raw source ratings for tooltip display.
 */
export type InstructorScore = { composite: CompositeRating, rmp: RmpRating | null, bluebook: BlueBookRating | null, };
