// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A linked RMP profile in the detail view.
 */
export type LinkedRmpProfile = { linkId: number, legacyId: number, firstName: string, lastName: string, department: string | null, avgRating: number | null, avgDifficulty: number | null, numRatings: number, wouldTakeAgainPct: number | null, 
/**
 * Subject prefixes extracted from RMP reviews (queried live from rmp_reviews).
 */
reviewSubjects: Array<string>, 
/**
 * Distinct years in which this professor received reviews.
 */
reviewYears: Array<number>, };
