// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BluebookLinkListItem } from "./BluebookLinkListItem";
import type { BluebookLinkStats } from "./BluebookLinkStats";

/**
 * Response for the paginated link list.
 */
export type ListBluebookLinksResponse = { links: Array<BluebookLinkListItem>, total: number, page: number, perPage: number, stats: BluebookLinkStats, };
