// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BluebookLinkStatus } from "./BluebookLinkStatus";

/**
 * Query params for `GET /api/admin/bluebook/links`.
 */
export type ListBluebookLinksParams = { status: BluebookLinkStatus | null, search: string | null, page: number | null, perPage: number | null, };
