// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BluebookLinkListItem } from "./BluebookLinkListItem";
import type { BluebookLinkStats } from "./BluebookLinkStats";
import type { Page } from "./Page";

/**
 * Response for the paginated link list.
 */
export type ListBluebookLinksResponse = { page: Page<BluebookLinkListItem>, stats: BluebookLinkStats, };
