// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstructorListItem } from "./InstructorListItem";
import type { InstructorStats } from "./InstructorStats";
import type { Page } from "./Page";

/**
 * Response for the paginated instructor list.
 */
export type ListInstructorsResponse = { page: Page<InstructorListItem>, stats: InstructorStats, };
