// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RmpMatchStatus } from "./RmpMatchStatus";

export type ListInstructorsParams = { status: RmpMatchStatus | null, search: string | null, page: number | null, perPage: number | null, sort: string | null, };
