// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Physical location where a course section meets.
 */
export type MeetingLocation = { building: string | null, buildingDescription: string | null, room: string | null, campus: string | null, };
