// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of an automatic merge sweep.
 */
export type MergeStats = { merged: number, skipped: number, };
