// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetricsParams = { courseId: number | null, term: string | null, crn: string | null, range: string | null, limit: number, };
