// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Simple acknowledgement response for mutating operations.
 */
export type OkResponse = { ok: boolean, };
