// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Online delivery sub-variants.
 */
export type OnlineVariant = "Async" | "Sync" | "Mixed";
