// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One page of a list endpoint's results.
 *
 * Every paginated endpoint returns this shape, so a client can page through any of
 * them with the same code. `page` is 1-based.
 */
export type Page<T> = { items: Array<T>, total: number, page: number, perPage: number, };
