// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which portion of the semester a course section spans.
 */
export type PartOfTerm = { "type": "FullTerm" } | { "type": "FirstHalf" } | { "type": "SecondHalf" } | { "type": "Unknown", code: string, description: string, };
