// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicInstructorProfile } from "./PublicInstructorProfile";
import type { TeachingHistoryTerm } from "./TeachingHistoryTerm";

export type PublicInstructorProfileResponse = { instructor: PublicInstructorProfile, teachingHistory: Array<TeachingHistoryTerm>, };
