// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicInstructorListItem = { id: number, slug: string, displayName: string, email: string, subjects: Array<string>, avgRating: number | null, numRatings: number | null, rmpLegacyId: number | null, };
