// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicInstructorListItem } from "./PublicInstructorListItem";

export type PublicInstructorListResponse = { instructors: Array<PublicInstructorListItem>, total: number, page: number, perPage: number, };
