// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlueBookFull } from "./BlueBookFull";
import type { InstructorRating } from "./InstructorRating";
import type { RmpFull } from "./RmpFull";

export type PublicInstructorProfile = { id: number, slug: string, displayName: string, email: string | null, firstName: string | null, lastName: string | null, subjects: Array<string>, rmp: RmpFull | null, bluebook: BlueBookFull | null, rating: InstructorRating | null, };
