// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full BlueBook summary for instructor detail pages.
 */
export type PublicBlueBookSummary = { 
/**
 * Calibrated BlueBook score on the RMP scale (1-5), from `instructor_scores.calibrated_bb`.
 */
normalizedRating: number | null, avgInstructorRating: number, avgCourseRating: number | null, totalResponses: number, evalCount: number, };
