// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicInstructorListParams = { search: string | null, subject: string | null, sort: string, page: number, perPage: number, };
