// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RmpListSummary } from "./RmpListSummary";

export type PublicInstructorListItem = { id: number, slug: string, displayName: string, email: string | null, subjects: Array<string>, rmp: RmpListSummary | null, };
