// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data source for an instructor rating.
 *
 * `BlueBook` lowercases to `bluebook` under both attributes, which is the only
 * spelling `instructor_scores.source` still holds.
 */
export type RatingSource = "both" | "rmp" | "bluebook";
