// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data source for an instructor rating.
 */
export type RatingSource = "both" | "rmp" | "bluebook";
