// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for the rescore operation.
 */
export type RescoreResponse = { 
/**
 * Total instructors processed (excludes confirmed/rejected).
 */
totalProcessed: number, 
/**
 * Pending candidate rows deleted before regeneration.
 */
deletedPendingCandidates: number, 
/**
 * Auto-generated links deleted before regeneration.
 */
deletedAutoLinks: number, 
/**
 * Candidates inserted in this run.
 */
candidatesCreated: number, 
/**
 * Instructors auto-linked (score >= threshold).
 */
autoMatched: number, 
/**
 * Instructors with candidates below auto-accept threshold (status = 'pending').
 */
pendingReview: number, skippedUnparseable: number, skippedNoCandidates: number, };
