// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Review state of a single `rmp_match_candidates` row.
 */
export type RmpCandidateStatus = "pending" | "accepted" | "rejected";
