// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full RateMyProfessors summary for instructor detail pages.
 */
export type RmpFull = { avgRating: number | null, avgDifficulty: number | null, wouldTakeAgainPct: number | null, numRatings: number | null, legacyId: number, };
