// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight RMP summary for instructor list cards.
 *
 * Present whenever an RMP profile link exists. Rating fields are `None` when the
 * profile has no reviews.
 */
export type RmpListSummary = { avgRating: number | null, numRatings: number | null, legacyId: number, };
