// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Match status for RMP instructor matching.
 *
 * Stored as VARCHAR, so `serde` and `strum` must spell every variant the same way:
 * one drives the API and TypeScript union, the other the column round-trip.
 */
export type RmpMatchStatus = "unmatched" | "pending" | "auto" | "confirmed" | "rejected";
