// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Match status for RMP instructor matching.
 *
 * Stored as VARCHAR in the database - this enum is for Rust API types
 * and TypeScript bindings only (no sqlx::Type derive).
 */
export type RmpMatchStatus = "unmatched" | "pending" | "auto" | "confirmed" | "rejected";
