// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RateMyProfessors rating summary for an instructor.
 */
export type RmpRating = { avgRating: number, numRatings: number, legacyId: number, isConfident: boolean, };
