// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RateMyProfessors rating summary for an instructor.
 *
 * Present whenever an RMP profile link exists. Rating fields are `None` when the
 * profile has no reviews (0 ratings / 0.0 average).
 */
export type RmpRating = { avgRating: number | null, numRatings: number | null, legacyId: number, isConfident: boolean, };
