// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a subject is or is not due for a scrape, derived rather than stored.
 */
export type ScheduleState = "eligible" | "cooldown" | "paused";
