// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data source for a composite score.
 */
export type ScoreSource = "both" | "rmp" | "bb";
