// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Breakdown of individual scoring signals.
 */
export type ScoreBreakdown = { name: number, 
/**
 * Department string similarity (from RMP profile).
 */
department: number, 
/**
 * Review course code overlap (from RMP reviews).
 */
reviewCourses: number, 
/**
 * Merged subject evidence: `max(department, review_courses)`.
 * This is the value actually used in the composite score - the stronger
 * of the two subject-alignment signals.
 */
subject: number, uniqueness: number, volume: number, };
