// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScrapeJobStatus } from "./ScrapeJobStatus";
import type { ScrapePriority } from "./ScrapePriority";
import type { TargetType } from "./TargetType";

export type ScrapeJobsFilter = { status?: Array<ScrapeJobStatus> | null, priority?: Array<ScrapePriority> | null, targetType?: Array<TargetType> | null, term?: string | null, subject?: Array<string> | null, };
