// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScrapeJobDto } from "./ScrapeJobDto";
import type { ScrapeJobStatus } from "./ScrapeJobStatus";

/**
 * Events broadcast when scrape job state changes.
 */
export type ScrapeJobEvent = { "type": "created", job: ScrapeJobDto, } | { "type": "locked", id: number, lockedAt: string, status: ScrapeJobStatus, } | { "type": "completed", id: number, } | { "type": "retried", id: number, retryCount: number, queuedAt: string, status: ScrapeJobStatus, } | { "type": "exhausted", id: number, } | { "type": "deleted", id: number, };
