// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchParams = { term: string, subject: Array<string>, query: string | null, courseNumberLow: number | null, courseNumberHigh: number | null, openOnly: boolean, instructionalMethod: Array<string>, campus: Array<string>, limit: number, offset: number, 
/**
 * Ordered sort keys, comma separated, `-` prefixed for descending.
 *
 * Taken as a string so a bad key answers with a shaped error rather than
 * serde's own rejection, which carries neither a code nor a message the
 * client can read.
 */
sort: string | null, waitCountMax: number | null, days: Array<string>, timeStart: string | null, timeEnd: string | null, partOfTerm: Array<string>, attributes: Array<string>, creditHourMin: number | null, creditHourMax: number | null, instructor: Array<string>, };
