// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CourseResponse } from "./CourseResponse";

export type SearchResponse = { courses: Array<CourseResponse>, totalCount: number, offset: number, limit: number, };
