// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeDescription } from "./CodeDescription";
import type { FilterRanges } from "./FilterRanges";
import type { SearchOptionsReference } from "./SearchOptionsReference";
import type { TermResponse } from "./TermResponse";

/**
 * Response for the consolidated search-options endpoint.
 */
export type SearchOptionsResponse = { terms: Array<TermResponse>, subjects: Array<CodeDescription>, reference: SearchOptionsReference, ranges: FilterRanges, };
