// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a season within a term
 */
export type Season = "Fall" | "Spring" | "Summer";
