// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A linked section reference (e.g. lab linked to a lecture).
 */
export type SectionLink = { identifier: string, };
