// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health status of a service.
 */
export type ServiceStatus = "starting" | "active" | "connected" | "disabled" | "error";
