// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scrape target for [`TargetType::SingleCrn`]: one section.
 */
export type SingleCrnTarget = { crn: string, term: string | null, };
