// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortKey } from "./SortKey";

/**
 * A sort key as offered to the client: what it is, and what each way round means.
 */
export type SortKeyOption = { key: SortKey, ascLabel: string, descLabel: string, };
