// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Column to sort search results by.
 */
export type SortColumn = "course_code" | "title" | "instructor" | "time" | "seats";
