// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An orderable quantity.
 *
 * Deliberately not a column: several keys may share one column's header, and
 * some belong to no column at all.
 */
export type SortKey = "course_code" | "title" | "instructor_name" | "instructor_rating" | "start_time" | "end_time" | "duration" | "weekly_minutes" | "days" | "seats_open" | "fill_ratio" | "wait_count";
