// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatsParams = { period: string, 
/**
 * Optional term code to filter stats (e.g., "202510"). If omitted, includes all terms.
 */
term: string | null, };
