// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditLogEntry } from "./AuditLogEntry";
import type { ScrapeJobEvent } from "./ScrapeJobEvent";

export type StreamDelta = { "stream": "scrapeJobs", event: ScrapeJobEvent, } | { "stream": "auditLog", entries: Array<AuditLogEntry>, };
