// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamFilter } from "./StreamFilter";
import type { StreamKind } from "./StreamKind";

export type StreamClientMessage = { "type": "subscribe", request_id: string, stream: StreamKind, filter?: StreamFilter | null, } | { "type": "modify", request_id: string, subscription_id: string, filter?: StreamFilter | null, } | { "type": "unsubscribe", request_id: string, subscription_id: string, } | { "type": "ping", request_id?: string | null, timestamp?: string | null, };
