// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditLogEntry } from "./AuditLogEntry";
import type { ScrapeJobDto } from "./ScrapeJobDto";
import type { ScraperStatsResponse } from "./ScraperStatsResponse";
import type { SubjectSummary } from "./SubjectSummary";
import type { TimeseriesPoint } from "./TimeseriesPoint";

export type StreamSnapshot = { "stream": "scrapeJobs", jobs: Array<ScrapeJobDto>, } | { "stream": "auditLog", entries: Array<AuditLogEntry>, } | { "stream": "scraperStats", stats: ScraperStatsResponse, } | { "stream": "scraperTimeseries", points: Array<TimeseriesPoint>, period: string, bucket: string, } | { "stream": "scraperSubjects", subjects: Array<SubjectSummary>, };
