// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditLogEntry } from "./AuditLogEntry";
import type { ScrapeJobEvent } from "./ScrapeJobEvent";
import type { ScraperStatsResponse } from "./ScraperStatsResponse";
import type { SubjectSummary } from "./SubjectSummary";
import type { TimeseriesPoint } from "./TimeseriesPoint";

export type StreamDelta = { "stream": "scrapeJobs", event: ScrapeJobEvent, } | { "stream": "auditLog", entries: Array<AuditLogEntry>, } | { "stream": "scraperStats", stats: ScraperStatsResponse, } | { "stream": "scraperTimeseries", changed: Array<TimeseriesPoint>, } | { "stream": "scraperSubjects", changed: Array<SubjectSummary>, removed: Array<string>, };
