// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamDelta } from "./StreamDelta";
import type { StreamErrorCode } from "./StreamErrorCode";
import type { StreamKind } from "./StreamKind";
import type { StreamSnapshot } from "./StreamSnapshot";

export type StreamServerMessage = { "type": "ready", protocol_version: number, } | { "type": "subscribed", request_id: string, subscription_id: string, stream: StreamKind, } | { "type": "modified", request_id: string, subscription_id: string, } | { "type": "unsubscribed", request_id: string, subscription_id: string, } | { "type": "snapshot", subscription_id: string, snapshot: StreamSnapshot, } | { "type": "delta", subscription_id: string, delta: StreamDelta, } | { "type": "error", request_id: string | null, code: StreamErrorCode, message: string, } | { "type": "pong", request_id: string | null, timestamp: string | null, };
