// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditLogFilter } from "./AuditLogFilter";
import type { ScrapeJobsFilter } from "./ScrapeJobsFilter";
import type { ScraperStatsFilter } from "./ScraperStatsFilter";
import type { ScraperTimeseriesFilter } from "./ScraperTimeseriesFilter";

export type StreamFilter = { "stream": "scrapeJobs" } & ScrapeJobsFilter | { "stream": "auditLog" } & AuditLogFilter | { "stream": "scraperStats" } & ScraperStatsFilter | { "stream": "scraperTimeseries" } & ScraperTimeseriesFilter | { "stream": "scraperSubjects", };
