// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditLogEntry } from "./AuditLogEntry";
import type { ScrapeJobDto } from "./ScrapeJobDto";

export type StreamSnapshot = { "stream": "scrapeJobs", jobs: Array<ScrapeJobDto>, } | { "stream": "auditLog", entries: Array<AuditLogEntry>, };
