// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubjectResultEntry } from "./SubjectResultEntry";

export type SubjectDetailResponse = { subject: string, results: Array<SubjectResultEntry>, };
