// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scrape target for [`TargetType::Subject`]: every section of one subject in one term.
 */
export type SubjectTarget = { subject: string, 
/**
 * Term code (e.g. "202510"). Legacy jobs omit it and fall back to the current term.
 */
term: string | null, };
