// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubjectResultEntry = { id: number, 
/**
 * ISO-8601 UTC timestamp when the scrape job completed (e.g., "2024-01-15T10:30:00Z")
 */
completedAt: string, durationMs: number, success: boolean, errorMessage: string | null, coursesFetched: number | null, coursesChanged: number | null, coursesUnchanged: number | null, auditsGenerated: number | null, metricsGenerated: number | null, };
