// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CourseSuggestion } from "./CourseSuggestion";
import type { InstructorSuggestion } from "./InstructorSuggestion";

export type SuggestResponse = { courses: Array<CourseSuggestion>, instructors: Array<InstructorSuggestion>, };
