// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CourseRangeTarget } from "./CourseRangeTarget";
import type { CrnListTarget } from "./CrnListTarget";
import type { SingleCrnTarget } from "./SingleCrnTarget";
import type { SubjectTarget } from "./SubjectTarget";

/**
 * The payload of a scrape job, discriminated by the row's [`TargetType`].
 *
 * The stored JSON carries no tag, so variants are ordered most-specific first:
 * deserialization picks the first shape whose required fields are all present.
 */
export type TargetPayload = CourseRangeTarget | CrnListTarget | SingleCrnTarget | SubjectTarget;
