// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of target for a scrape job, determining how the payload is interpreted.
 */
export type TargetType = "subject" | "courseRange" | "crnList" | "singleCrn";
