// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TeachingHistoryCourse = { subject: string, courseNumber: string, title: string, sectionCount: number, };
