// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeachingHistoryCourse } from "./TeachingHistoryCourse";

export type TeachingHistoryTerm = { termSlug: string, termDescription: string, courses: Array<TeachingHistoryCourse>, };
