// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `POST /api/admin/terms/sync`.
 */
export type TermSyncResponse = { inserted: number, updated: number, };
