// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbTerm } from "./DbTerm";

/**
 * Response for `GET /api/admin/terms`.
 */
export type TermsListResponse = { terms: Array<DbTerm>, };
