// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbTerm } from "./DbTerm";

/**
 * Response for `POST /api/admin/terms/:code/enable` and `disable`.
 */
export type TermUpdateResponse = { success: boolean, term: DbTerm | null, };
