// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimeRange = { 
/**
 * ISO-8601 UTC timestamp (e.g., "2024-01-15T10:30:00Z")
 */
start: string, 
/**
 * ISO-8601 UTC timestamp (e.g., "2024-01-15T12:30:00Z")
 */
end: string, };
