// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimeseriesPoint = { 
/**
 * ISO-8601 UTC timestamp for this data point (e.g., "2024-01-15T10:00:00Z")
 */
timestamp: string, scrapeCount: number, successCount: number, errorCount: number, coursesChanged: number, avgDurationMs: number, };
