// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineSlot } from "./TimelineSlot";

export type TimelineResponse = { 
/**
 * 15-minute slots with per-subject enrollment totals, sorted by time.
 */
slots: Array<TimelineSlot>, 
/**
 * All subject codes present in the returned data.
 */
subjects: Array<string>, };
