// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineSlot = { 
/**
 * ISO-8601 timestamp at the start of this 15-minute bucket.
 */
time: string, 
/**
 * Subject code → total enrollment in this slot.
 */
subjects: Record<string, number>, };
