// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Time range for meetings
 */
export type TimeRange = { start: string, end: string, };
