// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineSlot = { 
/**
 * ISO-8601 UTC timestamp at the start of this 15-minute bucket (e.g., "2024-01-15T10:30:00Z")
 */
time: string, 
/**
 * Subject code → total enrollment in this slot.
 */
subjects: Record<string, number>, };
