// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineRange } from "./TimelineRange";

export type TimelineRequest = { ranges: Array<TimelineRange>, };
