// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoreBreakdown } from "./ScoreBreakdown";

/**
 * A top-candidate summary shown in the instructor list view.
 */
export type TopCandidateResponse = { rmpLegacyId: number, score: number, scoreBreakdown: ScoreBreakdown, firstName: string, lastName: string, department: string | null, avgRating: number | null, numRatings: number, 
/**
 * Instructor already holding this profile, when it is not this one.
 */
claimedBy: string | null, };
