// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoreBreakdown } from "./ScoreBreakdown";

/**
 * A top-candidate summary shown in the instructor list view.
 */
export type TopCandidateResponse = { rmpLegacyId: number, score: number | null, scoreBreakdown: ScoreBreakdown | null, firstName: string | null, lastName: string | null, department: string | null, avgRating: number | null, numRatings: number | null, };
