// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrendSample } from "./TrendSample";

export type TrendsResponse = { 
/**
 * CRN to its oldest-first samples. Sections with no recorded history are absent.
 */
trends: { [key in string]?: Array<TrendSample> }, };
